# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/\
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: | 
        CURRENT_DIR=$(pwd)
        npm ci
        npm run build:dev
        cp -r . ../cust_pack
        cd ../cust_pack 
        rm -r ./source 
        rm -r ./types 
        npm pack
        cd "$CURRENT_DIR"
        
        

    - name: Create GitHub Release-Common
      uses: softprops/action-gh-release@v2
      with:
        tag_name: development-build
        name: Development Build ${{ github.run_number }}
        files: | 
          ../cust_pack/*.tgz
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE }}

